version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"

  backend:
    build: ./backend
    ports:
      - "3000:3000"

  ordersDB:
    image: mysql:8
    container_name: orders_db
    environment:
      MYSQL_ROOT_PASSWORD: 123  
      MYSQL_DATABASE: orders  
      MYSQL_USER: root  
      MYSQL_PASSWORD: 123  
    ports:
      - "3306:3306"  

  productsDB:
    image: mysql:8
    container_name: products_db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: products
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
