events {}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        root /usr/share/nginx/html;  # Default root

        # Serve JavaScript files
        location /scripts {
            alias /usr/share/nginx/scripts;  # Adjust path as needed
        }

        # Serve CSS files
        location /styles {
            alias /usr/share/nginx/styles;
        }

        # Serve HTML files directly from /html
        location / {
            try_files $uri $uri/ =404;
        }

        # Forward API requests to the backend service
        location /api/ {
            proxy_pass http://backend:3000/;  # Forward API requests to the backend container
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
