events {}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        root /usr/share/nginx/html;  # Default root

        # Serve JavaScript files
        location /scripts {
            alias /usr/share/nginx/scripts;  # Adjust path as needed
        }

        # Serve CSS files
        location /styles {
            alias /usr/share/nginx/styles;
        }

        # Serve HTML files directly from /html
        location / {
            try_files $uri $uri/ =404;
        }
    }
}
